import "server-only";
import { cacheLife, cacheTag } from "next/cache";
import { getStaticNames } from "@/lib/static/lookup";
import type { NameBook } from "@/lib/static/names";
import { toItemText, type ItemText } from "@/lib/static/tooltip-text";
import { must } from "@/lib/supabase/result";
import { getCachedSupabase } from "@/lib/supabase/server";
import { readNewestCuratedFile } from "./curated-files";
import type { BisRole, ItemKind } from "@/lib/static/game";
import { CHAMPION_BIS_FILE, championBisFileSchema } from "./schemas";
import { formatIssue, parseYaml, suggestApiNames, type SeedIssue } from "./validate";

/**
 * Champion best-in-slot builds for `/bis` (architecture §7.4, §8). The file is
 * generated by `pnpm sync:bis` and read from the repo during prerender, like the
 * patch brief and the openers — but every `api_name` in it is resolved against the
 * static tables first, so a renamed item fails the build instead of rendering a raw
 * api name on the page.
 */

export type BisItemRef = { name: string; iconUrl: string | null };

export type BisItem = BisItemRef & {
  apiName: string;
  /** Recipe, for the tooltip. Empty for an item with no components stored. */
  components: BisItemRef[];
  /** Trait name, for emblems. */
  grantsTrait: string | null;
  /** `items.kind`, so the tooltip can say "Artifact" or "Radiant". Null when not stored. */
  kind: ItemKind | null;
};

export type BisChampion = {
  apiName: string;
  name: string;
  cost: number;
  iconUrl: string | null;
  role: BisRole;
  /** Exactly three items. May repeat one: two of the same item is a legal board. */
  primary: BisItem[];
  secondary: BisItem[];
  /** Best-placing artifacts and radiants. Empty when none cleared the sync's floor. */
  special: BisItem[];
  notes: string | null;
  /** Average placement of the primary build, when the sync measured one. */
  avgPlace: number | null;
  games: number | null;
};

export type ChampionBis = {
  patch: string;
  title: string;
  /** Provenance line from the generated file, printed under the page title. */
  source: string | null;
  champions: BisChampion[];
  /**
   * Tooltip stats and description by item api name — once per item, however many
   * builds hold it, rather than repeated on every `BisItem` in the payload.
   */
  itemText: Record<string, ItemText>;
};

/** Extra item columns the tooltip needs, which `NameBook` doesn't carry. */
export type BisItemDetails = ReadonlyMap<
  string,
  { components: string[]; grantsTrait: string | null; kind?: ItemKind; text?: ItemText | null }
>;

export type BisReferences = { names: NameBook; itemDetails: BisItemDetails };

/**
 * Pure: YAML text plus the reference tables → resolved rows, or the issues that
 * stopped them. Beyond the schema: every champion and item exists, no champion is
 * listed twice, no "alternative" is already in the primary build, and no artifact or
 * radiant is listed twice.
 */
export function validateChampionBis(input: {
  /** Repo-relative path, used in issues. */
  file: string;
  text: string;
  refs: BisReferences;
}): { bis?: ChampionBis; issues: SeedIssue[] } {
  const { file, refs } = input;
  const yaml = parseYaml(file, input.text);
  if (yaml.syntaxIssues.length) return { issues: yaml.syntaxIssues };

  const parsed = championBisFileSchema.safeParse(yaml.data);
  if (!parsed.success) {
    return { issues: parsed.error.issues.map((issue) => yaml.issue(issue.path, issue.message)) };
  }
  const data = parsed.data;
  const issues: SeedIssue[] = [];

  const didYouMean = (name: string, candidates: Iterable<readonly [string, { name: string }]>) => {
    const suggestions = suggestApiNames(name, candidates);
    return suggestions.length ? `. Did you mean ${suggestions.join(" or ")}?` : "";
  };

  const listedAt = new Map<string, number>();
  const champions = data.champions.map((row, index): BisChampion => {
    const at = (...rest: PropertyKey[]) => ["champions", index, ...rest];

    const first = listedAt.get(row.api_name);
    if (first !== undefined) {
      issues.push(yaml.issue(at("api_name"), `${row.api_name} already has a build at champions[${first}]`));
    } else {
      listedAt.set(row.api_name, index);
    }

    const champion = refs.names.champions[row.api_name];
    if (!champion) {
      const candidates = Object.entries(refs.names.champions);
      issues.push(yaml.issue(at("api_name"), `unknown champion "${row.api_name}"${didYouMean(row.api_name, candidates)}`));
    }

    const toItem = (apiName: string, path: PropertyKey[]): BisItem => {
      const item = refs.names.items[apiName];
      if (!item) {
        issues.push(yaml.issue(path, `unknown item "${apiName}"${didYouMean(apiName, Object.entries(refs.names.items))}`));
      }
      const details = refs.itemDetails.get(apiName);
      return {
        apiName,
        name: item?.name ?? apiName,
        iconUrl: item?.iconUrl ?? null,
        components: (details?.components ?? []).map((component) => ({
          name: refs.names.items[component]?.name ?? component,
          iconUrl: refs.names.items[component]?.iconUrl ?? null,
        })),
        grantsTrait: details?.grantsTrait ? (refs.names.traits[details.grantsTrait]?.name ?? details.grantsTrait) : null,
        kind: details?.kind ?? null,
      };
    };

    // A build may hold two of the same item, so duplicates inside `primary_bis` are
    // legal. An "alternative" already in the build is not: it offers no alternative.
    const primary = row.primary_bis.map((apiName, i) => toItem(apiName, at("primary_bis", i)));
    const inPrimary = new Set(row.primary_bis);
    const secondary = row.secondary_bis.map((apiName, i) => {
      const path = at("secondary_bis", i);
      if (inPrimary.has(apiName)) {
        issues.push(yaml.issue(path, `${apiName} is already in primary_bis, so it is not an alternative`));
      }
      return toItem(apiName, path);
    });
    const seenSpecial = new Set<string>();
    const special = row.special_bis.map((apiName, i) => {
      const path = at("special_bis", i);
      if (seenSpecial.has(apiName)) issues.push(yaml.issue(path, `${apiName} is listed twice in special_bis`));
      seenSpecial.add(apiName);
      return toItem(apiName, path);
    });

    return {
      apiName: row.api_name,
      name: champion?.name ?? row.api_name,
      cost: champion?.cost ?? 0,
      iconUrl: champion?.iconUrl ?? null,
      role: row.role,
      primary,
      secondary,
      special,
      notes: row.notes ?? null,
      avgPlace: row.avg_place ?? null,
      games: row.games ?? null,
    };
  });

  if (issues.length) return { issues };

  const itemText: Record<string, ItemText> = {};
  for (const champion of champions) {
    for (const item of [...champion.primary, ...champion.secondary, ...champion.special]) {
      const text = refs.itemDetails.get(item.apiName)?.text;
      if (text) itemText[item.apiName] = text;
    }
  }

  return {
    issues,
    bis: {
      patch: data.patch,
      title: data.title ?? "Best in slot",
      source: data.source ?? null,
      champions,
      itemText,
    },
  };
}

/**
 * Tagged `static` because every name, icon and cost it renders comes from the static
 * tables, so `pnpm sync:static` has to be able to refresh it. The YAML itself only
 * changes with a deploy.
 *
 * A missing file returns null and `/bis` renders its empty state. A file naming an
 * item or champion that isn't there **throws**, failing the build the way
 * `seed:curated` aborts — `sync:bis` validates the shape before it writes, so a
 * broken reference here means the static tables moved under it.
 */
export async function getChampionBis(): Promise<ChampionBis | null> {
  "use cache";
  cacheTag("static");
  cacheLife("days");

  const found = await readNewestCuratedFile(CHAMPION_BIS_FILE);
  if (!found) return null;

  const { names } = await getStaticNames();
  const { file, text } = found;

  // Only the items this file actually names: `items` holds 771 rows in Set 18, and
  // the recipes and text are needed for the tooltip alone.
  const used = new Set<string>();
  const parsed = championBisFileSchema.safeParse(parseYaml(file, text).data);
  if (parsed.success) {
    for (const row of parsed.data.champions) {
      for (const item of [...row.primary_bis, ...row.secondary_bis, ...row.special_bis]) used.add(item);
    }
  }
  const rows = used.size
    ? must(
        await getCachedSupabase()
          .from("items")
          .select("api_name, components, grants_trait, kind, description, stats, text_source")
          .in("api_name", [...used]),
        "bis items",
      )
    : [];
  const itemDetails: BisItemDetails = new Map(
    rows.map((row) => [
      row.api_name,
      { components: row.components, grantsTrait: row.grants_trait, kind: row.kind, text: toItemText(row) },
    ]),
  );

  const { bis, issues } = validateChampionBis({ file, text, refs: { names, itemDetails } });
  if (!bis) {
    throw new Error(`Invalid ${file}:\n${issues.map((issue) => `  ${formatIssue(issue)}`).join("\n")}`);
  }
  return bis;
}
