import { Document, isMap, isScalar, isSeq, parse } from "yaml";
import { BOARD_COLS, BOARD_ROWS, MAX_UNIT_ITEMS, type CompStyle, type TierRank } from "@/lib/static/game";
import { MAX_CARRY_PRIORITY } from "./schemas";

/**
 * External comp feed → curated comp YAML (`pnpm sync:meta`, architecture §7.2).
 * Pure: the script fetches, resolves api names and supplies plain rows.
 *
 * A comp is a much larger claim than a tier-list row — a board, items, star goals and
 * an order to build them in — so nearly everything here is a documented rule for
 * turning "what people played" into "what to play". Where the feed is silent the rule
 * is to leave the field out rather than invent it; `guide` is the only prose, and it is
 * assembled from the feed's own numbers.
 */

/** The feed numbers its hexes `cell_1`…`cell_28`. */
export const BOARD_CELLS = BOARD_ROWS * BOARD_COLS;

/** First line of a generated comp. A file without it is hand-written and never touched. */
export const GENERATED_COMP_MARKER = "# GENERATED by `pnpm sync:meta`";

/**
 * `cell_N` → our row/col, or undefined for a cell off the board.
 *
 * The feed counts cells 1-28 from the **back** row forward, which is the opposite of
 * our rows (0 is the front line). Verified against real data rather than assumed: in
 * every comp checked, tanks sit in cells 22-28 and ranged carries in cells 1-7, so
 * cells 1-7 are row 3.
 */
export function cellToHex(cell: number): { row: number; col: number } | undefined {
  if (!Number.isInteger(cell) || cell < 1 || cell > BOARD_CELLS) return undefined;
  return { row: BOARD_ROWS - 1 - Math.floor((cell - 1) / BOARD_COLS), col: (cell - 1) % BOARD_COLS };
}

/** `"cell_12"` → 12. Anything else reads as no cell rather than throwing. */
export function parseCell(cell: string): number | undefined {
  const match = /^cell_(\d+)$/.exec(cell);
  return match ? Number(match[1]) : undefined;
}

/** One candidate hex for a unit, with how often it was played there. */
export type CellCount = { cell: string; count: number };

/** One item build the feed saw on a unit. */
export type UnitBuild = { items: string[]; count: number; avgPlace: number };

/** A unit of the comp, as the script hands it over: feed rows already resolved. */
export type CompUnitInput = {
  apiName: string;
  /** Share of the comp's boards this unit appeared on, 0-1. */
  share: number;
  /** Star level played most often. */
  star: number;
  cells: readonly CellCount[];
  builds: readonly UnitBuild[];
};

export type PlacedUnit = {
  apiName: string;
  row: number;
  col: number;
  star: number;
  carry: boolean;
  priority?: number;
  items: string[];
};

/**
 * Every unit onto its own hex, most-played first.
 *
 * Two units often share a favourite hex, so the board is filled greedily: the unit on
 * more boards takes it, and the other falls through to its own next-most-played hex.
 * A unit whose every recorded hex is taken gets the first free one — the schema
 * requires unique hexes, and a comp is more useful with a unit in a slightly wrong
 * place than not written at all.
 */
export function placeUnits(units: readonly CompUnitInput[]): { apiName: string; row: number; col: number }[] {
  const taken = new Set<string>();
  const key = (row: number, col: number) => `${row},${col}`;
  const placed: { apiName: string; row: number; col: number }[] = [];

  for (const unit of [...units].sort((a, b) => b.share - a.share || a.apiName.localeCompare(b.apiName))) {
    let hex: { row: number; col: number } | undefined;
    for (const candidate of [...unit.cells].sort((a, b) => b.count - a.count || a.cell.localeCompare(b.cell))) {
      const cell = parseCell(candidate.cell);
      const at = cell === undefined ? undefined : cellToHex(cell);
      if (at && !taken.has(key(at.row, at.col))) {
        hex = at;
        break;
      }
    }
    hex ??= firstFreeHex(taken);
    if (!hex) continue; // A full board; 28 units cannot happen, but never write a bad hex.
    taken.add(key(hex.row, hex.col));
    placed.push({ apiName: unit.apiName, ...hex });
  }
  return placed;
}

function firstFreeHex(taken: ReadonlySet<string>): { row: number; col: number } | undefined {
  for (let row = 0; row < BOARD_ROWS; row++) {
    for (let col = 0; col < BOARD_COLS; col++) {
      if (!taken.has(`${row},${col}`)) return { row, col };
    }
  }
  return undefined;
}

/**
 * The items a unit should hold: its best-sampled build that `allowBuild` accepts.
 *
 * Builds come from real boards, so one can hold an item our tables don't know, or an
 * emblem for a trait the unit already has — both of which `validateComp` rejects. The
 * predicate takes the whole build rather than one item because an emblem clash is a
 * property of the combination, and a rejected build is skipped entirely: writing a
 * build with its offending item stripped out would be a build nobody actually played.
 */
export function pickItems(
  unit: CompUnitInput,
  allowBuild: (apiName: string, items: readonly string[]) => boolean,
): string[] {
  const best = [...unit.builds]
    .filter((build) => build.items.length > 0 && build.items.length <= MAX_UNIT_ITEMS)
    .sort((a, b) => b.count - a.count || a.items.join().localeCompare(b.items.join()))
    .find((build) => allowBuild(unit.apiName, build.items));
  return best ? [...best.items] : [];
}

/** A unit on the board, plus what `assignCarries` needs to rank it. */
export type CarryCandidate = PlacedUnit & {
  share: number;
  builds: readonly UnitBuild[];
};

/**
 * Carries, and the order to build them in.
 *
 * A carry is a unit whose **written** build fills its item slots. Deciding this from
 * the build that is actually in the file, rather than from how many items the unit
 * usually holds, is what keeps the two consistent: a unit whose most-played build is a
 * single Thief's Gloves is not written as a three-item carry just because its average
 * board carries three.
 *
 * Priority runs best-sampled first and stops at three, because past third it stops
 * meaning anything (`MAX_CARRY_PRIORITY`), and only a unit that ended up with items
 * can take one — `validateComp` rejects a priority on an empty-handed unit.
 */
export function assignCarries(units: readonly CarryCandidate[]): PlacedUnit[] {
  const holders = units
    .filter((unit) => unit.items.length >= MAX_UNIT_ITEMS)
    .sort((a, b) => (b.builds[0]?.count ?? 0) - (a.builds[0]?.count ?? 0) || a.apiName.localeCompare(b.apiName));

  // Nobody held a full set. A comp still needs one carry to validate, so the most
  // itemised unit takes the role rather than the whole comp being dropped.
  const ranked = holders.length
    ? holders
    : units
        .filter((unit) => unit.items.length > 0)
        .sort((a, b) => b.items.length - a.items.length || b.share - a.share || a.apiName.localeCompare(b.apiName))
        .slice(0, 1);

  const priorityOf = new Map(ranked.slice(0, MAX_CARRY_PRIORITY).map((unit, index) => [unit.apiName, index + 1]));
  const carries = new Set(ranked.map((unit) => unit.apiName));

  return units.map((unit) => {
    const priority = priorityOf.get(unit.apiName);
    return {
      apiName: unit.apiName,
      row: unit.row,
      col: unit.col,
      star: unit.star,
      items: unit.items,
      carry: carries.has(unit.apiName),
      ...(priority === undefined ? {} : { priority }),
    };
  });
}

/** A carry as the style rule sees it: what it costs and how far it is levelled. */
export type StyleUnit = { apiName: string; cost: number; star: number; carry: boolean };

/**
 * Which of the six `comp_style` values this comp is.
 *
 * Reroll first, because it is the strongest signal: a three-starred cheap carry means
 * the comp is built by rolling at a level, whatever level it ends on. Otherwise the
 * modal final level decides, and a comp that ends below 8 is `flex` rather than a
 * "fast" anything.
 */
export function compStyle(finalLevel: number, units: readonly StyleUnit[]): CompStyle {
  const reroll = units.find((unit) => unit.carry && unit.star >= 3 && unit.cost >= 1 && unit.cost <= 3);
  if (reroll) return `reroll_${reroll.cost as 1 | 2 | 3}`;
  if (finalLevel >= 9) return "fast9";
  if (finalLevel === 8) return "fast8";
  return "flex";
}

/**
 * 1 easy, 2 medium, 3 hard. The feed does not rate difficulty, so this is a rule
 * rather than a measurement: what makes a comp hard is needing a level or a 3-star you
 * may not get. Reaching 9 is the hardest ask, a three-star cheap carry the next.
 */
export function compDifficulty(style: CompStyle, finalLevel: number): number {
  if (style === "fast9" || finalLevel >= 10) return 3;
  if (style.startsWith("reroll_")) return 2;
  return style === "fast8" ? 2 : 1;
}

/**
 * A display name → the slug that is also the file name and the URL.
 * Apostrophes and dots close up (`Kog'Maw` → `kogmaw`); anything else becomes a dash.
 */
export function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/['".]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export type CompSource = {
  slug: string;
  name: string;
  tier: TierRank;
  style: CompStyle;
  difficulty: number;
  patch: string;
  order: number;
  gem: boolean;
  summary: string;
  avgPlace: number;
  /** A percentage, the way the schema takes it. */
  pickRate: number;
  levelRecommended: number;
  earlyUnits: readonly string[];
  flexUnits: readonly string[];
  board: readonly PlacedUnit[];
  guide: string;
  /** Header comment lines, under the generated-file warning. */
  provenance: readonly string[];
};

const GENERATED_WARNING = [
  "GENERATED by `pnpm sync:meta`. Hand edits are overwritten on the next sync.",
  "To keep a comp of your own, delete the marker line above: a file without it is",
  "treated as hand-written, and is never overwritten or pruned.",
];

/** Two decimals, without the trailing zeros a fixed-width format would leave. */
const round2 = (value: number) => Math.round(value * 100) / 100;

/**
 * The file text: header comment, then the shape `compFileSchema` accepts.
 * Board rows are written as flow maps, one unit per line — both how the hand-written
 * comps read, and what keeps a moved unit to a one-line diff.
 */
export function buildCompYaml(source: CompSource): string {
  const doc = new Document({
    slug: source.slug,
    name: source.name,
    tier: source.tier,
    style: source.style,
    difficulty: source.difficulty,
    patch: source.patch,
    order: source.order,
    ...(source.gem ? { gem: true } : {}),
    summary: source.summary,
    avg_place: round2(source.avgPlace),
    pick_rate: round2(source.pickRate),
    level_recommended: source.levelRecommended,
    ...(source.earlyUnits.length ? { early_units: [...source.earlyUnits] } : {}),
    ...(source.flexUnits.length ? { flex_units: [...source.flexUnits] } : {}),
    board: source.board.map((unit) => ({
      unit: unit.apiName,
      row: unit.row,
      col: unit.col,
      ...(unit.star === 2 ? {} : { star: unit.star }),
      ...(unit.carry ? { carry: true } : {}),
      ...(unit.priority === undefined ? {} : { priority: unit.priority }),
      ...(unit.items.length ? { items: unit.items } : {}),
    })),
    guide: source.guide,
  });

  // One unit per line: a block map per unit would make a nine-unit board 40 lines.
  for (const key of ["early_units", "flex_units", "board"] as const) {
    const node = doc.get(key, true);
    if (!isSeq(node)) continue;
    if (key === "board") {
      for (const item of node.items) if (isMap(item)) item.flow = true;
    } else {
      node.flow = true;
    }
  }
  // A multi-paragraph guide as one quoted scalar would be unreadable in a diff.
  const guide = doc.get("guide", true);
  if (isScalar(guide)) guide.type = "BLOCK_LITERAL";

  const header = [...GENERATED_WARNING, "", ...source.provenance].map((line) => (line ? `# ${line}` : "#")).join("\n");
  return `${header}\n${doc.toString({ lineWidth: 0 })}`;
}

/** True when a file on disk was written by this script, so it may be rewritten. */
export function isGenerated(text: string): boolean {
  return text.startsWith(GENERATED_COMP_MARKER);
}

/**
 * What a reader of the comp cares about, for the "write only when it changed" check.
 *
 * The provenance header carries a sample size that grows between any two runs, and
 * `summary` quotes it too, so comparing file text would rewrite every comp every sync.
 */
export function compFingerprint(text: string): string {
  let data: unknown;
  try {
    data = parse(text);
  } catch {
    return "";
  }
  if (typeof data !== "object" || data === null) return "";
  // Sorted, so a reordered key is not mistaken for a changed comp; `summary` is left
  // out because it quotes the sample size, which grows between any two runs.
  return JSON.stringify(
    Object.entries(data as Record<string, unknown>)
      .filter(([key]) => key !== "summary")
      .sort(([a], [b]) => a.localeCompare(b)),
  );
}
